### ISSUE TITLE
存在しないメソッドのためエラー

### ISSUE THREAD

**Issue by makotokushiyama** [makotokushiyama/debug_lesson#1]
"Yeah, it’s barking."
1
"tom"
debg_lesson_1.rb:35:in `proc': undefined method `+' for nil:NilClass (NoMethodError)
	from debg_lesson_1.rb:46:in `<main>'

＋メソッドはNilClassに定義されていないメソッドであったために、エラーが起きた。

**Comment by ghost** [comment]
OKです。
補足として、NilClassのnilオブジェクトに対して定義されていない、とするとより細やかな回答になると思います。

**Comment by makotokushiyama** [comment]
正しい出力は「bsd=>mit」であるが、実際は「NoMethodError」となっている。この出力をしている箇所は「p path[0] + "=>" +  @data[path[0]].to_s」である。

**Comment by makotokushiyama** [comment]
修正です。

正しい出力は「bsd”=>”mit」であるが、実際は「NoMethodError」となっている。この出力をしている箇所は「p path[0] + "=>" + @DaTa[path[0]].to_s」である。
